# Generated by Django 6.0.4 on 2026-04-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedEquipment',
            fields=[
            ],
            options={
                'verbose_name': 'a damaged equipment',
                'verbose_name_plural': 'Damaged Equipments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.equipment',),
        ),
    ]
