# Generated by Django 6.0.4 on 2026-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_damagedequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='branch',
            field=models.ManyToManyField(related_name='equipment_branch', to='main.branch'),
        ),
    ]
