# Generated by Django 6.0.4 on 2026-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_equipment_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='members',
            field=models.ManyToManyField(to='main.member'),
        ),
    ]
