# Generated by Django 6.0.4 on 2026-04-22 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gymclass_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='branch',
        ),
        migrations.AddField(
            model_name='equipment',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_branch', to='main.branch'),
            preserve_default=False,
        ),
    ]
