# Generated by Django 6.0.4 on 2026-08-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gymclass_trainer', to='club.trainer'),
        ),
    ]
